# Generated by Django 4.1.4 on 2022-12-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amextransaction',
            name='reimbursable',
            field=models.BooleanField(default=False),
        ),
    ]
